export function getModelsArray(ctx = {}) {
    const models = [
      {
        id: 'claude-sonnet-4-5-20250929',
        name: 'Claude Sonnet 4.5',
        description: 'Latest anthropic model',
        provider: 'anthropic',
        model: 'claude-sonnet-4-5-20250929',
        max_tokens: 25000, // 64,000 is the real max, but then users will hit max windows all the time
        context_window_tokens_limit: 200000,
        stream: true,
        fast: false,
        cmd_k_support: true,
        cmd_l_support: true,
        auth_header: 'x-api-key',
        auth_prefix: '',
        reasoning: false,
        agent_supported: true,
        research_supported: false,
        image_supported: true,
        pdf_supported: true,
        tier: 2,
        input_cost_per_m_tokens: 3.0,
        output_cost_per_m_tokens: 15.0,
        cache_write_cost_per_m_tokens: 3.75,
        cache_read_cost_per_m_tokens: 0.3,
        read_timeout: 60 * 5,
        write_timeout: 60 * 5,
        connect_timeout: 60,
        dropdown_category: 'regular',
        redacted_thinking: true,
      },
      {
        id: 'gpt-5-codex',
        name: 'GPT-5 Codex',
        description: 'Code-focused GPT-5 tuned for software development',
        provider: 'openai',
        model: 'gpt-5-codex',
        max_tokens: 16384,
        context_window_tokens_limit: 400000,
        stream: true,
        fast: false,
        cmd_k_support: false,
        cmd_l_support: true,
        auth_header: 'Authorization',
        auth_prefix: 'Bearer',
        reasoning: true,
        agent_supported: true,
        research_supported: false,
        image_supported: true,
        pdf_supported: false,
        tier: 2,
        input_cost_per_m_tokens: 1.25,
        cache_read_cost_per_m_tokens: 0.125,
        output_cost_per_m_tokens: 10.0,
        read_timeout: 60 * 5,
        write_timeout: 60 * 5,
        connect_timeout: 60,
        dropdown_category: 'regular',
        redacted_thinking: true,
      },
      {
        id: 'gpt-5',
        name: 'GPT-5',
        description: "OpenAI's latest frontier model",
        provider: null,
        model: 'gpt-5',
        max_tokens: 16384,
        context_window_tokens_limit: 400000,
        stream: true,
        fast: false,
        cmd_k_support: true,
        cmd_l_support: true,
        auth_header: 'Authorization',
        auth_prefix: 'Bearer',
        reasoning: true,
        agent_supported: true,
        research_supported: false,
        image_supported: true,
        pdf_supported: true,
        tier: 2,
        input_cost_per_m_tokens: 1.25,
        cache_read_cost_per_m_tokens: 0.125,
        output_cost_per_m_tokens: 10.0,
        read_timeout: 60 * 5,
        write_timeout: 60 * 5,
        connect_timeout: 60,
        dropdown_category: 'regular',
        redacted_thinking: true,
      },
      {
        id: 'gpt-5-fast',
        name: 'GPT-5 (Priority)',
        description: 'GPT-5 via OpenAI Priority processing (lower latency, premium pricing)',
        provider: 'openai',
        model: 'gpt-5',
        max_tokens: 16384,
        context_window_tokens_limit: 400000,
        stream: true,
        fast: false,
        cmd_k_support: false,
        cmd_l_support: true,
        auth_header: 'Authorization',
        auth_prefix: 'Bearer',
        reasoning: true,
        agent_supported: true,
        research_supported: false,
        image_supported: true,
        pdf_supported: true,
        tier: 2,
        input_cost_per_m_tokens: 2.5,
        cache_read_cost_per_m_tokens: 0.25,
        output_cost_per_m_tokens: 20.0,
        read_timeout: 60 * 5,
        write_timeout: 60 * 5,
        connect_timeout: 60,
        dropdown_category: 'regular',
        redacted_thinking: true,
      },
      {
        id: 'claude-haiku-4-5-20251001',
        name: 'Claude Haiku 4.5',
        description: 'Fast and cost effective anthropic model',
        provider: 'anthropic',
        model: 'claude-haiku-4-5-20251001',
        max_tokens: 25000,
        context_window_tokens_limit: 200000,
        stream: true,
        fast: true,
        cmd_k_support: true,
        cmd_l_support: true,
        auth_header: 'x-api-key',
        auth_prefix: '',
        reasoning: false,
        agent_supported: true,
        research_supported: false,
        image_supported: true,
        pdf_supported: true,
        tier: 2,
        input_cost_per_m_tokens: 1.0,
        output_cost_per_m_tokens: 5.0,
        cache_write_cost_per_m_tokens: 1.25,
        cache_read_cost_per_m_tokens: 0.1,
        read_timeout: 60 * 5,
        write_timeout: 60 * 5,
        connect_timeout: 60,
        dropdown_category: 'regular',
        redacted_thinking: false,
      },
      {
        id: 'claude-sonnet-4-20250514',
        name: 'Claude Sonnet 4',
        description: 'Best general purpose coding agent',
        provider: 'anthropic',
        model: 'claude-sonnet-4-20250514',
        max_tokens: 25000, // 64,000 is the real max, but then users will hit max windows all the time
        context_window_tokens_limit: 200000,
        stream: true,
        fast: false,
        cmd_k_support: true,
        cmd_l_support: true,
        auth_header: 'x-api-key',
        auth_prefix: '',
        reasoning: false,
        agent_supported: true,
        research_supported: false,
        image_supported: true,
        pdf_supported: true,
        tier: 2,
        input_cost_per_m_tokens: 3.0,
        output_cost_per_m_tokens: 15.0,
        cache_write_cost_per_m_tokens: 3.75,
        cache_read_cost_per_m_tokens: 0.3,
        read_timeout: 60 * 5,
        write_timeout: 60 * 5,
        connect_timeout: 60,
        dropdown_category: 'regular',
        redacted_thinking: false,
      },
      {
        id: 'gpt-5-mini',
        name: 'GPT-5-mini',
        description: "OpenAI's latest frontier model mini",
        provider: null,
        model: 'gpt-5-mini',
        max_tokens: 16384,
        context_window_tokens_limit: 400000,
        stream: true,
        fast: false,
        cmd_k_support: true,
        cmd_l_support: true,
        auth_header: 'Authorization',
        auth_prefix: 'Bearer',
        reasoning: true,
        agent_supported: true,
        research_supported: false,
        image_supported: true,
        pdf_supported: false,
        tier: 3,
        input_cost_per_m_tokens: 0.25,
        cache_read_cost_per_m_tokens: 0.025,
        output_cost_per_m_tokens: 2.0,
        read_timeout: 60 * 5,
        write_timeout: 60 * 5,
        connect_timeout: 60,
        dropdown_category: 'regular',
        redacted_thinking: true,
      },
      {
        id: 'gpt-oss-120b',
        name: 'GPT-OSS-120b',
        description: 'Lightning fast, OpenAI largest open source model',
        provider: 'cerebras',
        model: 'gpt-oss-120b',
        max_tokens: -1, // means unbounded for cerebras only
        context_window_tokens_limit: 131000,
        stream: true,
        fast: false,
        cmd_k_support: true,
        cmd_l_support: true,
        auth_header: 'Authorization',
        auth_prefix: 'Bearer',
        reasoning: false,
        agent_supported: false,
        research_supported: false,
        image_supported: false,
        pdf_supported: false,
        tier: 3,
        input_cost_per_m_tokens: 1.0,
        output_cost_per_m_tokens: 1.0,
        read_timeout: 60 * 5,
        write_timeout: 60 * 5,
        connect_timeout: 60,
        dropdown_category: 'regular',
        redacted_thinking: false,
      },
      {
        id: 'gpt-4.1',
        name: 'GPT-4.1',
        provider: 'openai',
        model: 'gpt-4.1',
        max_tokens: 16384,
        context_window_tokens_limit: 1000000,
        stream: true,
        fast: false,
        cmd_k_support: true,
        cmd_l_support: true,
        auth_header: 'Authorization',
        auth_prefix: 'Bearer',
        reasoning: false,
        agent_supported: true,
        research_supported: true,
        image_supported: true,
        pdf_supported: false,
        tier: 3,
        input_cost_per_m_tokens: 2.0,
        cache_read_cost_per_m_tokens: 0.5,
        output_cost_per_m_tokens: 8.0,
        read_timeout: 60 * 5,
        write_timeout: 60 * 5,
        connect_timeout: 60,
        dropdown_category: 'old',
        redacted_thinking: false,
      },
      {
        id: 'claude-3.7-sonnet',
        name: 'Claude-3.7 Sonnet',
        provider: 'anthropic',
        model: 'claude-3-7-sonnet-latest',
        max_tokens: 25000,
        context_window_tokens_limit: 200000,
        stream: true,
        fast: false,
        cmd_k_support: true,
        cmd_l_support: true,
        auth_header: 'x-api-key',
        auth_prefix: '',
        reasoning: false,
        agent_supported: true,
        research_supported: false,
        image_supported: true,
        pdf_supported: true,
        tier: 3,
        input_cost_per_m_tokens: 3.0,
        output_cost_per_m_tokens: 15.0,
        cache_write_cost_per_m_tokens: 3.75,
        cache_read_cost_per_m_tokens: 0.3,
        read_timeout: 60 * 5,
        write_timeout: 60 * 5,
        connect_timeout: 60,
        dropdown_category: 'old',
        redacted_thinking: false,
      },
      {
        id: 'claude-3.5-sonnet',
        name: 'Claude-3.5 Sonnet',
        provider: 'anthropic',
        model: 'claude-3-5-sonnet-latest',
        max_tokens: 8192,
        context_window_tokens_limit: 200000,
        stream: true,
        fast: false,
        cmd_k_support: true,
        cmd_l_support: true,
        auth_header: 'x-api-key',
        auth_prefix: '',
        reasoning: false,
        agent_supported: true,
        research_supported: true,
        image_supported: true,
        pdf_supported: true,
        tier: 3,
        input_cost_per_m_tokens: 3.0,
        output_cost_per_m_tokens: 15.0,
        cache_write_cost_per_m_tokens: 3.75,
        cache_read_cost_per_m_tokens: 0.3,
        read_timeout: 60 * 5,
        write_timeout: 60 * 5,
        connect_timeout: 60,
        dropdown_category: 'old',
        redacted_thinking: false,
      },
      {
        id: 'claude-opus-4-1-20250805',
        name: 'Claude Opus 4.1',
        description: 'Latest version with improved performance for deep analysis',
        provider: 'anthropic',
        model: 'claude-opus-4-1-20250805',
        max_tokens: 25000,
        context_window_tokens_limit: 200000,
        stream: true,
        fast: false,
        cmd_k_support: true,
        cmd_l_support: true,
        auth_header: 'x-api-key',
        auth_prefix: '',
        reasoning: false,
        agent_supported: true,
        research_supported: false,
        image_supported: true,
        pdf_supported: true,
        tier: 1,
        input_cost_per_m_tokens: 15.0,
        output_cost_per_m_tokens: 75.0,
        cache_write_cost_per_m_tokens: 18.75,
        cache_read_cost_per_m_tokens: 1.5,
        read_timeout: 60 * 5,
        write_timeout: 60 * 5,
        connect_timeout: 60,
        dropdown_category: 'research',
        redacted_thinking: false,
      },
      {
        id: 'claude-opus-4-20250514',
        name: 'Claude Opus 4',
        description: 'Better for deep analysis than Sonnet, but slower coding agent',
        provider: 'anthropic',
        model: 'claude-opus-4-20250514',
        max_tokens: 25000,
        context_window_tokens_limit: 200000,
        stream: true,
        fast: false,
        cmd_k_support: true,
        cmd_l_support: true,
        auth_header: 'x-api-key',
        auth_prefix: '',
        reasoning: false,
        agent_supported: true,
        research_supported: false,
        image_supported: true,
        pdf_supported: true,
        tier: 1,
        input_cost_per_m_tokens: 15.0,
        output_cost_per_m_tokens: 75.0,
        cache_write_cost_per_m_tokens: 18.75,
        cache_read_cost_per_m_tokens: 1.5,
        read_timeout: 60 * 5,
        write_timeout: 60 * 5,
        connect_timeout: 60,
        dropdown_category: 'research',
        redacted_thinking: false,
      },
      {
        id: 'o3',
        name: 'OpenAI-o3',
        provider: 'openai',
        model: 'o3',
        max_tokens: 100000,
        context_window_tokens_limit: 200000,
        stream: true,
        fast: false,
        cmd_k_support: true,
        cmd_l_support: true,
        auth_header: 'Authorization',
        auth_prefix: 'Bearer',
        reasoning: true,
        agent_supported: true,
        research_supported: true,
        image_supported: true,
        pdf_supported: false,
        tier: 3,
        input_cost_per_m_tokens: 2.0,
        cache_read_cost_per_m_tokens: 0.5,
        output_cost_per_m_tokens: 8.0,
        read_timeout: 60 * 5,
        write_timeout: 60 * 5,
        connect_timeout: 60,
        dropdown_category: 'old',
        redacted_thinking: false,
      },
      {
        id: 'o4-mini',
        name: 'OpenAI-o4-mini',
        provider: 'openai',
        model: 'o4-mini',
        max_tokens: 100000,
        context_window_tokens_limit: 200000,
        stream: true,
        fast: false,
        cmd_k_support: true,
        cmd_l_support: true,
        auth_header: 'Authorization',
        auth_prefix: 'Bearer',
        reasoning: true,
        agent_supported: true,
        research_supported: true,
        image_supported: true,
        pdf_supported: false,
        tier: 3,
        input_cost_per_m_tokens: 1.1,
        cache_read_cost_per_m_tokens: 0.275,
        output_cost_per_m_tokens: 4.4,
        read_timeout: 60 * 5,
        write_timeout: 60 * 5,
        connect_timeout: 60,
        dropdown_category: 'old',
        redacted_thinking: false,
      },
      {
        id: 'gpt-5-pro',
        name: 'GPT-5 Pro',
        description: 'Great for single queries that require deep thinking',
        provider: 'openai',
        model: 'gpt-5-pro',
        max_tokens: 272000,
        context_window_tokens_limit: 400000,
        stream: true,
        fast: false,
        cmd_k_support: false,
        cmd_l_support: true,
        auth_header: 'Authorization',
        auth_prefix: 'Bearer',
        reasoning: true,
        agent_supported: true,
        research_supported: true,
        image_supported: true,
        pdf_supported: false,
        tier: 1,
        input_cost_per_m_tokens: 15.0,
        output_cost_per_m_tokens: 120.0,
        read_timeout: 60 * 15, // 15 minutes
        write_timeout: 60 * 15, // 15 minutes
        connect_timeout: 60,
        dropdown_category: 'research',
      },
      {
        id: 'o3-mini',
        name: 'OpenAI-o3-mini',
        provider: 'openai',
        model: 'o3-mini',
        max_tokens: 100000,
        context_window_tokens_limit: 200000,
        stream: true,
        fast: false,
        cmd_k_support: true,
        cmd_l_support: true,
        auth_header: 'Authorization',
        auth_prefix: 'Bearer',
        reasoning: true,
        agent_supported: true,
        research_supported: true,
        image_supported: true,
        pdf_supported: false,
        tier: 3,
        input_cost_per_m_tokens: 1.1,
        cache_read_cost_per_m_tokens: 0.55,
        output_cost_per_m_tokens: 4.4,
        read_timeout: 60 * 5,
        write_timeout: 60 * 5,
        connect_timeout: 60,
        dropdown_category: 'old',
        redacted_thinking: false,
      },
      {
        id: 'gpt-4o',
        name: 'GPT-4o',
        provider: 'openai',
        model: 'gpt-4o',
        max_tokens: 16384,
        context_window_tokens_limit: 128000,
        stream: true,
        fast: false,
        cmd_k_support: true,
        cmd_l_support: true,
        auth_header: 'Authorization',
        auth_prefix: 'Bearer',
        reasoning: false,
        agent_supported: true,
        research_supported: true,
        image_supported: true,
        pdf_supported: false,
        tier: 3,
        input_cost_per_m_tokens: 2.5,
        cache_read_cost_per_m_tokens: 1.25,
        output_cost_per_m_tokens: 10.0,
        read_timeout: 60 * 5,
        write_timeout: 60 * 5,
        connect_timeout: 60,
        dropdown_category: 'old',
        redacted_thinking: false,
      },
      {
        id: 'gpt-5-low',
        name: 'GPT-5 (Low Reasoning)',
        description: "OpenAI's latest frontier model - less reasoning",
        provider: null,
        model: 'gpt-5-low',
        max_tokens: 16384,
        context_window_tokens_limit: 400000,
        stream: true,
        fast: false,
        cmd_k_support: true,
        cmd_l_support: true,
        auth_header: 'Authorization',
        auth_prefix: 'Bearer',
        reasoning: true,
        agent_supported: true,
        research_supported: false,
        image_supported: true,
        pdf_supported: true,
        tier: 2,
        input_cost_per_m_tokens: 1.25,
        cache_read_cost_per_m_tokens: 0.125,
        output_cost_per_m_tokens: 10.0,
        read_timeout: 60 * 5,
        write_timeout: 60 * 5,
        connect_timeout: 60,
        dropdown_category: 'regular',
        redacted_thinking: true,
      },
      {
        id: 'gpt-5-low-fast',
        name: 'GPT-5 (Low Reasoning, Priority)',
        description: 'GPT-5 Low via OpenAI Priority processing (lower latency, premium pricing)',
        provider: 'openai',
        model: 'gpt-5-low',
        max_tokens: 16384,
        context_window_tokens_limit: 400000,
        stream: true,
        fast: false,
        cmd_k_support: false,
        cmd_l_support: true,
        auth_header: 'Authorization',
        auth_prefix: 'Bearer',
        reasoning: true,
        agent_supported: true,
        research_supported: false,
        image_supported: true,
        pdf_supported: true,
        tier: 2,
        input_cost_per_m_tokens: 2.5,
        cache_read_cost_per_m_tokens: 0.25,
        output_cost_per_m_tokens: 20.0,
        read_timeout: 60 * 5,
        write_timeout: 60 * 5,
        connect_timeout: 60,
        dropdown_category: 'regular',
        redacted_thinking: true,
      },
      {
        id: 'gpt-5-high',
        name: 'GPT-5 (High Reasoning)',
        description: "OpenAI's latest frontier model - more reasoning",
        provider: null,
        model: 'gpt-5-high',
        max_tokens: 16384,
        context_window_tokens_limit: 400000,
        stream: true,
        fast: false,
        cmd_k_support: true,
        cmd_l_support: true,
        auth_header: 'Authorization',
        auth_prefix: 'Bearer',
        reasoning: true,
        agent_supported: true,
        research_supported: false,
        image_supported: true,
        pdf_supported: true,
        tier: 2,
        input_cost_per_m_tokens: 1.25,
        cache_read_cost_per_m_tokens: 0.125,
        output_cost_per_m_tokens: 10.0,
        read_timeout: 60 * 10, // Longer timeout for deep reasoning
        write_timeout: 60 * 10,
        connect_timeout: 60,
        dropdown_category: 'regular',
        redacted_thinking: true,
      },
      {
        id: 'gpt-5-high-fast',
        name: 'GPT-5 (High Reasoning, Priority)',
        description: 'GPT-5 High via OpenAI Priority processing (lower latency, premium pricing)',
        provider: 'openai',
        model: 'gpt-5-high',
        max_tokens: 16384,
        context_window_tokens_limit: 400000,
        stream: true,
        fast: false,
        cmd_k_support: false,
        cmd_l_support: true,
        auth_header: 'Authorization',
        auth_prefix: 'Bearer',
        reasoning: true,
        agent_supported: true,
        research_supported: false,
        image_supported: true,
        pdf_supported: true,
        tier: 2,
        input_cost_per_m_tokens: 2.5,
        cache_read_cost_per_m_tokens: 0.25,
        output_cost_per_m_tokens: 20.0,
        read_timeout: 60 * 10,
        write_timeout: 60 * 10,
        connect_timeout: 60,
        dropdown_category: 'regular',
        redacted_thinking: true,
      },
      {
        id: 'gpt-5-codex-low',
        name: 'GPT-5 Codex (Low Reasoning)',
        description: 'Code-focused GPT-5 tuned for software development - less reasoning',
        provider: null,
        model: 'gpt-5-codex-low',
        max_tokens: 16384,
        context_window_tokens_limit: 400000,
        stream: true,
        fast: false,
        cmd_k_support: false,
        cmd_l_support: true,
        auth_header: 'Authorization',
        auth_prefix: 'Bearer',
        reasoning: true,
        agent_supported: true,
        research_supported: false,
        image_supported: true,
        pdf_supported: false,
        tier: 2,
        input_cost_per_m_tokens: 1.25,
        cache_read_cost_per_m_tokens: 0.125,
        output_cost_per_m_tokens: 10.0,
        read_timeout: 60 * 5,
        write_timeout: 60 * 5,
        connect_timeout: 60,
        dropdown_category: 'regular',
        redacted_thinking: true,
      },
      {
        id: 'gpt-5-codex-high',
        name: 'GPT-5 Codex (High Reasoning)',
        description: 'Code-focused GPT-5 tuned for software development - more reasoning',
        provider: null,
        model: 'gpt-5-codex-high',
        max_tokens: 16384,
        context_window_tokens_limit: 400000,
        stream: true,
        fast: false,
        cmd_k_support: false,
        cmd_l_support: true,
        auth_header: 'Authorization',
        auth_prefix: 'Bearer',
        reasoning: true,
        agent_supported: true,
        research_supported: false,
        image_supported: true,
        pdf_supported: false,
        tier: 2,
        input_cost_per_m_tokens: 1.25,
        cache_read_cost_per_m_tokens: 0.125,
        output_cost_per_m_tokens: 10.0,
        read_timeout: 60 * 10, // Longer timeout for deep reasoning
        write_timeout: 60 * 10,
        connect_timeout: 60,
        dropdown_category: 'regular',
        redacted_thinking: true,
      },
      {
        id: 'claude-sonnet-4-5-1m',
        name: 'Claude Sonnet 4.5 (1M)',
        description: 'Latest anthropic model with 1M context (2x pricing over 200k tokens)',
        provider: 'anthropic',
        model: 'claude-sonnet-4-5-1m',
        max_tokens: 25000,
        context_window_tokens_limit: 1000000,
        stream: true,
        fast: false,
        cmd_k_support: true,
        cmd_l_support: true,
        auth_header: 'x-api-key',
        auth_prefix: '',
        reasoning: false,
        agent_supported: true,
        research_supported: false,
        image_supported: true,
        pdf_supported: true,
        tier: 2,
        input_cost_per_m_tokens: 3.0,
        output_cost_per_m_tokens: 15.0,
        cache_write_cost_per_m_tokens: 3.75,
        cache_read_cost_per_m_tokens: 0.3,
        read_timeout: 60 * 5,
        write_timeout: 60 * 5,
        connect_timeout: 60,
        dropdown_category: 'regular',
        context_pricing: true,
        context_pricing_threshold: 200000,
        context_input_multiplier: 2.0,
        context_output_multiplier: 1.5,
        context_cache_write_multiplier: 2.0,
        context_cache_read_multiplier: 2.0,
        redacted_thinking: false,
      },
      {
        id: 'claude-sonnet-4-1m',
        name: 'Claude Sonnet 4 (1M)',
        description:
          'Best general purpose coding agent with 1M context (2x pricing over 200k tokens)',
        provider: 'anthropic',
        model: 'claude-sonnet-4-1m',
        max_tokens: 25000,
        context_window_tokens_limit: 1000000,
        stream: true,
        fast: false,
        cmd_k_support: true,
        cmd_l_support: true,
        auth_header: 'x-api-key',
        auth_prefix: '',
        reasoning: false,
        agent_supported: true,
        research_supported: false,
        image_supported: true,
        pdf_supported: true,
        tier: 2,
        input_cost_per_m_tokens: 3.0,
        output_cost_per_m_tokens: 15.0,
        cache_write_cost_per_m_tokens: 3.75,
        cache_read_cost_per_m_tokens: 0.3,
        read_timeout: 60 * 5,
        write_timeout: 60 * 5,
        connect_timeout: 60,
        dropdown_category: 'regular',
        context_pricing: true,
        context_pricing_threshold: 200000,
        context_input_multiplier: 2.0,
        context_output_multiplier: 1.5,
        context_cache_write_multiplier: 2.0,
        context_cache_read_multiplier: 2.0,
      },
    ];
    return models;
}